// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN5p5UJXFfCbq8ZL1sVbjMyb0GMXntkHU',
    appId: '1:793715499459:web:6839c46d9250ccd302dd76',
    messagingSenderId: '793715499459',
    projectId: 'healthlink-5fffe',
    authDomain: 'healthlink-5fffe.firebaseapp.com',
    storageBucket: 'healthlink-5fffe.appspot.com',
    measurementId: 'G-VK2KRF9N84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiL1le4z4t9Nt7f-XkI6McwoEVeqtjvCE',
    appId: '1:793715499459:android:fd3f2ee1e2f0116802dd76',
    messagingSenderId: '793715499459',
    projectId: 'healthlink-5fffe',
    storageBucket: 'healthlink-5fffe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjATyocu54AeNN6VNzrs8cMmLYFqx9LnQ',
    appId: '1:793715499459:ios:087b0a082e42e09202dd76',
    messagingSenderId: '793715499459',
    projectId: 'healthlink-5fffe',
    storageBucket: 'healthlink-5fffe.appspot.com',
    iosBundleId: 'com.example.healthLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjATyocu54AeNN6VNzrs8cMmLYFqx9LnQ',
    appId: '1:793715499459:ios:087b0a082e42e09202dd76',
    messagingSenderId: '793715499459',
    projectId: 'healthlink-5fffe',
    storageBucket: 'healthlink-5fffe.appspot.com',
    iosBundleId: 'com.example.healthLink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN5p5UJXFfCbq8ZL1sVbjMyb0GMXntkHU',
    appId: '1:793715499459:web:72553f1c3dc9e59802dd76',
    messagingSenderId: '793715499459',
    projectId: 'healthlink-5fffe',
    authDomain: 'healthlink-5fffe.firebaseapp.com',
    storageBucket: 'healthlink-5fffe.appspot.com',
    measurementId: 'G-8NZ2BY8N3Z',
  );
}
